name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 18 * * *" # UTC 18:00 = 上海时间 02:00
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

# 2. 获取上一次成功的 workflow run ID
      - name: Get previous run ID
        id: get_run_id
        run: |
          # 使用 GitHub CLI 获取上一次成功的运行 ID
          PREVIOUS_RUN_ID=$(gh run list --workflow="Build and Push Docker Image" --status=success --json databaseId --jq '.[1].databaseId' || echo "")
          echo "Previous run ID: $PREVIOUS_RUN_ID"
          echo "run_id=$PREVIOUS_RUN_ID" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      # 3. 下载上次的提交哈希（如果存在）
      - name: Download last commit hash
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: last_commit
          path: ./ # 指定一个明确路径，避免覆盖其他文件
          run-id: ${{ steps.get_run_id.outputs.run_id }}  # 指定上一次运行的 ID
        continue-on-error: true

      - name: Check downloaded artifact
        run: |
          echo "Attempting to download last_commit artifact..."
          ls -la  # 调试：列出当前目录文件
          if [ -f "last_commit.txt" ]; then
            echo "Download successful, last_commit.txt found:"
            cat last_commit.txt
          else
            echo "Download failed or no artifact available."
          fi

      # 3. 检查目标仓库是否有更新
      - name: Check for updates in target repository
        id: check_updates
        run: |
          # 克隆目标仓库并指定分支
          git clone --branch main https://github.com/lobehub/lobe-chat.git target-repo
          cd target-repo
          LATEST_COMMIT=$(git rev-parse HEAD)  # 获取目标分支最新提交哈希
          cd ..

          # 检查是否存在上次的提交哈希文件
          if [ -f "last_commit.txt" ]; then
            LAST_KNOWN_COMMIT=$(cat last_commit.txt)
            echo "Last known commit: $LAST_KNOWN_COMMIT"
          else
            LAST_KNOWN_COMMIT=""
            echo "No previous commit hash found (first run or no artifact)."
          fi

          # 比较哈希，判断是否有更新
          if [ "$LATEST_COMMIT" != "$LAST_KNOWN_COMMIT" ]; then
            echo "Changes detected: $LATEST_COMMIT"
            echo "$LATEST_COMMIT" > last_commit.txt  # 更新哈希文件
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected, skipping build."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      # 8. 上传最新的提交哈希（仅在有更新时）
      - name: Upload last commit hash
        uses: actions/upload-artifact@v4
        with:
          name: last_commit # artifact 名称
          path: last_commit.txt # 上传的文件
